### ISSUE TITLE
Update Reference

### ISSUE THREAD

**Issue by BredrickSa** [Proless/MaterialXAMLDialogs#3]
Would it be possible to upgrade to version 4.2.1.2 of MaterialDesignThemes.Wpf?

**Comment by cwinland** [comment]
I agree. I have the latest version of MaterialDesignThemes installed and it is complaining about needing version 3.1.3.

**Comment by Proless** [comment]
MaterialDesignThemes.Wpf reference updated to 4.2.1 with the latest package version1.0.6
